CREATE TABLE IF NOT EXISTS `sim_scene` (
  `scene_id` bigint NOT NULL AUTO_INCREMENT COMMENT '场景ID',
  `scene_name` varchar(100) NOT NULL COMMENT '场景名称',
  `scene_type` char(1) DEFAULT '1' COMMENT '场景类型：1近海 2港口 3远海',
  `description` varchar(500) DEFAULT NULL COMMENT '场景描述',
  `map_url` varchar(255) DEFAULT NULL COMMENT '地图URL',
  `weather_conditions` varchar(100) DEFAULT NULL COMMENT '天气条件',
  `sea_conditions` varchar(100) DEFAULT NULL COMMENT '海况',
  `status` char(1) DEFAULT '0' COMMENT '状态：0正常 1停用',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) DEFAULT '0' COMMENT '删除标志：0存在 2删除',
  PRIMARY KEY (`scene_id`),
  UNIQUE KEY `uk_scene_name` (`scene_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='仿真场景信息表';

CREATE TABLE IF NOT EXISTS `uav_boat` (
  `boat_id` bigint NOT NULL AUTO_INCREMENT COMMENT '无人船ID',
  `boat_code` varchar(50) NOT NULL COMMENT '船编号',
  `boat_name` varchar(100) NOT NULL COMMENT '船名称',
  `boat_type` char(1) DEFAULT '1' COMMENT '船类型：1巡逻 2救援 3科研 4其他',
  `airport_id` bigint DEFAULT NULL COMMENT '所属机场ID',
  `longitude` decimal(10,6) DEFAULT NULL COMMENT '经度',
  `latitude` decimal(10,6) DEFAULT NULL COMMENT '纬度',
  `speed` decimal(10,2) DEFAULT NULL COMMENT '速度',
  `course` decimal(10,2) DEFAULT NULL COMMENT '航向',
  `status` char(1) DEFAULT '0' COMMENT '状态：0正常 1停用 2维护',
  `online_status` char(1) DEFAULT '0' COMMENT '在线状态：0在线 1离线',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) DEFAULT '0' COMMENT '删除标志：0存在 2删除',
  PRIMARY KEY (`boat_id`),
  UNIQUE KEY `uk_boat_code` (`boat_code`),
  KEY `idx_boat_airport_id` (`airport_id`),
  CONSTRAINT `fk_boat_airport_id` FOREIGN KEY (`airport_id`) REFERENCES `uav_airport` (`airport_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='无人船信息表';

CREATE TABLE IF NOT EXISTS `task` (
  `task_id` bigint NOT NULL AUTO_INCREMENT COMMENT '任务ID',
  `task_code` varchar(50) NOT NULL COMMENT '任务编号',
  `task_name` varchar(100) NOT NULL COMMENT '任务名称',
  `task_type` char(1) DEFAULT '1' COMMENT '任务类型：1巡逻 2救援 3科研 4其他',
  `scene_id` bigint DEFAULT NULL COMMENT '场景ID',
  `boat_id` bigint DEFAULT NULL COMMENT '船只ID',
  `status` char(1) DEFAULT '0' COMMENT '状态：0待执行 1执行中 2已完成 3失败 4暂停',
  `progress` int DEFAULT '0' COMMENT '进度',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `task_result` varchar(500) DEFAULT NULL COMMENT '任务结果',
  `task_description` varchar(500) DEFAULT NULL COMMENT '任务描述',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) DEFAULT '0' COMMENT '删除标志：0存在 2删除',
  PRIMARY KEY (`task_id`),
  UNIQUE KEY `uk_task_code` (`task_code`),
  KEY `idx_task_scene_id` (`scene_id`),
  KEY `idx_task_boat_id` (`boat_id`),
  CONSTRAINT `fk_task_scene_id` FOREIGN KEY (`scene_id`) REFERENCES `sim_scene` (`scene_id`),
  CONSTRAINT `fk_task_boat_id` FOREIGN KEY (`boat_id`) REFERENCES `uav_boat` (`boat_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='任务信息表';
